use crate::cdx::bond::Bond;
use crate::cdx_tags::bond_tags::*;
use crate::impl_tagged_object;

impl_tagged_object!(Bond, CDXOBJ_BOND, {
    begin: CDXPROP_BOND_BEGIN,
    end: CDXPROP_BOND_END,
    z_order: CDXPROP_Z_ORDER,
    ignore_warnings: CDXPROP_IGNORE_WARNINGS,
    chemical_warning: CDXPROP_CHEMICAL_WARNING,
    visible: CDXPROP_VISIBLE,
    foreground_color: CDXPROP_FOREGROUND_COLOR,
    background_color: CDXPROP_BACKGROUND_COLOR,
    bond_order: CDXPROP_BOND_ORDER,
    display: CDXPROP_BOND_DISPLAY,
    display2: CDXPROP_BOND_DISPLAY2,
    double_position: CDXPROP_BOND_DOUBLE_POSITION,
    topology: CDXPROP_BOND_RESTRICT_TOPOLOGY,
    rxn_participation: CDXPROP_BOND_RESTRICT_RXN_PARTICIPATION,
    begin_attach: CDXPROP_BOND_BEGIN_ATTACH,
    end_attach: CDXPROP_BOND_END_ATTACH,
    cip_stereochemistry: CDXPROP_BOND_CIP_STEREOCHEMISTRY,
    bond_circular_ordering: CDXPROP_BOND_CIRCULAR_ORDERING,
    show_query: CDXPROP_BOND_SHOW_QUERY,
    show_stereo: CDXPROP_BOND_SHOW_STEREO,
    crossing_bonds: CDXPROP_BOND_CROSSING_BONDS,
    show_rxn: CDXPROP_BOND_SHOW_RXN,
    bond_spacing: CDXPROP_BOND_SPACING,
    bond_length: CDXPROP_BOND_LENGTH,
    bold_width: CDXPROP_BOLD_WIDTH,
    line_width: CDXPROP_LINE_WIDTH,
    margin_width: CDXPROP_MARGIN_WIDTH,
    hash_spacing: CDXPROP_HASH_SPACING,
    label_font: CDXPROP_LABEL_STYLE_FONT,
    label_size: CDXPROP_LABEL_STYLE_SIZE,
    label_face: CDXPROP_LABEL_STYLE_FACE,
    bond_spacing_abs: CDXPROP_BOND_SPACING_ABS,
});
