use crate::cdx::graphic::Graphic;
use crate::cdx_tags::graphic_tags::*;
use crate::impl_tagged_object;

impl_tagged_object!(Graphic, CDXOBJ_GRAPHIC, {
    z_order: CDXPROP_Z_ORDER,
    ignore_warnings: CDXPROP_IGNORE_WARNINGS,
    chemical_warning: CDXPROP_CHEMICAL_WARNING,
    visible: CDXPROP_VISIBLE,
    superseded_by: CDXPROP_SUPERSEDED_BY,
    bounding_box: CDXPROP_BOUNDING_BOX,
    head_3d: CDXPROP_3D_HEAD,
    tail_3d: CDXPROP_3D_TAIL,
    foreground_color: CDXPROP_FOREGROUND_COLOR,
    background_color: CDXPROP_BACKGROUND_COLOR,
    bold_width: CDXPROP_BOLD_WIDTH,
    line_width: CDXPROP_LINE_WIDTH,
    caption_style: CDXPROP_CAPTION_STYLE,
    caption_style_font: CDXPROP_CAPTION_STYLE_FONT,
    caption_style_size: CDXPROP_CAPTION_STYLE_SIZE,
    caption_style_face: CDXPROP_CAPTION_STYLE_FACE,
    graphic_type: CDXPROP_GRAPHIC_TYPE,
    line_type: CDXPROP_LINE_TYPE,
    arrow_type: CDXPROP_ARROW_TYPE,
    rectangle_type: CDXPROP_RECTANGLE_TYPE,
    oval_type: CDXPROP_OVAL_TYPE,
    orbital_type: CDXPROP_ORBITAL_TYPE,
    bracket_type: CDXPROP_BRACKET_TYPE,
    symbol_type: CDXPROP_SYMBOL_TYPE,
    arrowhead_size: CDXPROP_ARROWHEAD_SIZE,
    arc_angular_size: CDXPROP_ARC_ANGULAR_SIZE,
    bracket_lip_size: CDXPROP_BRACKET_LIP_SIZE,
    bracket_usage: CDXPROP_BRACKET_USAGE,
    polymer_repeat_pattern: CDXPROP_POLYMER_REPEAT_PATTERN,
    polymer_flip_type: CDXPROP_POLYMER_FLIP_TYPE,
    corner_radius: CDXPROP_CORNER_RADIUS,
    frame_type: CDXPROP_FRAME_TYPE,
});
